import type { LucideIcon } from 'lucide-react';
import {
  Leaf, Gem, CloudFog, Moon, Feather, Sparkles, Compass, Flower2, Anchor, Shield,
  Bird, Flame, Droplets, BookOpen, Sunrise, Wind, Trees, Heart, Sun, Diamond, GraduationCap,
} from 'lucide-react';

export type NameEntry = {
  id: number;
  name: string;
  meaning: string;
  tags: string[];
  icon: LucideIcon;
  /** tailwind gradient stops for the card's pastel shimmer */
  gradient: string;
  /** accent color for glow + icon tint */
  accent: string;
  /** bento span classes */
  span: string;
};

export const NAMES: NameEntry[] = [
  {
    id: 1,
    name: 'Nghiêm Thu Sang',
    meaning: 'Ánh thu rẽ nhẹ qua đồi núi — một bình minh trở về mỗi mùa.',
    tags: ['#Autumn', '#Radiant', '#Dawn'],
    icon: Sunrise,
    gradient: 'from-rose-300/25 via-orange-200/15 to-amber-100/10',
    accent: 'rgba(255, 176, 136, 0.55)',
    span: 'md:col-span-3 md:row-span-2',
  },
  {
    id: 2,
    name: 'Nghiêm Như Ngọc',
    meaning: 'Quý như ngọc — sáng trong, bền bỉ và lặng lẽ hoàn mỹ.',
    tags: ['#Precious', '#Jade', '#Pure'],
    icon: Gem,
    gradient: 'from-emerald-200/25 via-teal-100/15 to-white/10',
    accent: 'rgba(150, 230, 200, 0.55)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 3,
    name: 'Nghiêm Như Sương',
    meaning: 'Như sương mai — dịu dàng, phù du, và không thể nắm giữ.',
    tags: ['#Mist', '#Pure', '#Soft'],
    icon: CloudFog,
    gradient: 'from-slate-200/20 via-sky-100/12 to-white/8',
    accent: 'rgba(200, 220, 240, 0.5)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 4,
    name: 'Nghiêm Như Nguyệt',
    meaning: 'Như ánh trăng — một hiện diện bạc soi rọi bóng tối.',
    tags: ['#Moon', '#Celestial', '#Silver'],
    icon: Moon,
    gradient: 'from-indigo-200/22 via-blue-100/14 to-slate-100/10',
    accent: 'rgba(170, 195, 255, 0.6)',
    span: 'md:col-span-3 md:row-span-2',
  },
  {
    id: 5,
    name: 'Nghiêm Như Quyên',
    meaning: 'Thướ tha như chim nhỏ bay lượn — mong manh và tự do.',
    tags: ['#Graceful', '#Bird', '#Free'],
    icon: Feather,
    gradient: 'from-rose-200/22 via-pink-100/14 to-white/8',
    accent: 'rgba(255, 180, 210, 0.55)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 6,
    name: 'Nghiêm Ngọc Ẩn',
    meaning: 'Ngọc ẩn — một kho báu giữ kín, sáng lên từ bên trong.',
    tags: ['#Hidden', '#Jade', '#Mystery'],
    icon: Sparkles,
    gradient: 'from-emerald-200/20 via-green-100/12 to-white/8',
    accent: 'rgba(160, 225, 190, 0.5)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 7,
    name: 'Nghiêm Phương Châm',
    meaning: 'Chiếc la bàn dẫn lối — người chỉ cho tim đường về nhà.',
    tags: ['#Guiding', '#Steady', '#True'],
    icon: Compass,
    gradient: 'from-amber-200/22 via-yellow-100/14 to-white/8',
    accent: 'rgba(245, 220, 160, 0.55)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 8,
    name: 'Nghiêm Ngọc Thảo',
    meaning: 'Cỏ ngọc — khiêm nhường, xanh tươi và lặng lẽ kiên cường qua mọi mùa.',
    tags: ['#Jade', '#Grass', '#Resilient'],
    icon: Leaf,
    gradient: 'from-emerald-200/22 via-lime-100/14 to-white/8',
    accent: 'rgba(170, 235, 175, 0.5)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 9,
    name: 'Nghiêm Hà An',
    meaning: 'Dòng sông bình yên — dòng nước êm ả mang mọi thứ nhẹ nhàng về phía trước.',
    tags: ['#River', '#Peace', '#Calm'],
    icon: Anchor,
    gradient: 'from-sky-200/22 via-cyan-100/14 to-white/8',
    accent: 'rgba(160, 215, 245, 0.55)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 10,
    name: 'Nghiêm Bảo Trâm',
    meaning: 'Chiếc trâm quý — một vật truyền đời của tĩnh lặng và duyên dáng.',
    tags: ['#Precious', '#Heirloom', '#Grace'],
    icon: Shield,
    gradient: 'from-violet-200/20 via-purple-100/12 to-white/8',
    accent: 'rgba(210, 185, 245, 0.5)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 11,
    name: 'Nghiêm Kim Tuyến',
    meaning: 'Sợi chỉ vàng — mảnh mai, rực rỡ, và luồn qua mọi điều bền vững.',
    tags: ['#Golden', '#Thread', '#Radiant'],
    icon: Flame,
    gradient: 'from-amber-200/24 via-orange-100/14 to-rose-100/10',
    accent: 'rgba(250, 205, 140, 0.6)',
    span: 'md:col-span-3 md:row-span-2',
  },
  {
    id: 12,
    name: 'Nghiêm Thanh Quyên',
    meaning: 'Chim có giọng trong — tiếng hót xé sạch bầu trời ban mai.',
    tags: ['#Clear', '#Bird', '#Song'],
    icon: Bird,
    gradient: 'from-teal-200/22 via-cyan-100/14 to-white/8',
    accent: 'rgba(150, 225, 220, 0.55)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 13,
    name: 'Nghiêm Hà Thu',
    meaning: 'Sông thu — mùa được phản chiếu trên dòng nước chảy.',
    tags: ['#Autumn', '#River', '#Reflective'],
    icon: Droplets,
    gradient: 'from-orange-200/22 via-rose-100/14 to-amber-100/10',
    accent: 'rgba(245, 180, 150, 0.55)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 14,
    name: 'Nghiêm Thanh Mai',
    meaning: 'Hoa mai trong — bông hoa đầu tiên của một năm lạnh và sáng.',
    tags: ['#Plum', '#Blossom', '#Clear'],
    icon: Flower2,
    gradient: 'from-rose-200/24 via-pink-100/14 to-white/8',
    accent: 'rgba(255, 175, 205, 0.6)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 15,
    name: 'Nghiêm Châu Loan',
    meaning: 'Viên ngọc trai giữa bầy chim gọi — hiếm, tròn và vang vọng dịu dàng.',
    tags: ['#Pearl', '#Rare', '#Echo'],
    icon: Diamond,
    gradient: 'from-cyan-200/20 via-sky-100/14 to-white/8',
    accent: 'rgba(170, 225, 240, 0.55)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 16,
    name: 'Nghiêm Anh Thư',
    meaning: 'Nữ thư sinh sáng sủa — những trang giấy giữ ánh sáng lâu sau khi đọc xong.',
    tags: ['#Bright', '#Scholar', '#Steady'],
    icon: BookOpen,
    gradient: 'from-amber-200/20 via-yellow-100/12 to-white/8',
    accent: 'rgba(240, 220, 160, 0.5)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 17,
    name: 'Nghiêm Thị Nguyệt',
    meaning: 'Sinh ra từ trăng — một nguồn sáng lặng lẽ không cần mặt trời.',
    tags: ['#Moon', '#Born', '#Luminary'],
    icon: Moon,
    gradient: 'from-blue-200/22 via-indigo-100/14 to-slate-100/10',
    accent: 'rgba(175, 195, 250, 0.6)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 18,
    name: 'Nghiêm Thu Hoài',
    meaning: 'Nỗi nhớ thu — mùa mà người ta cứ quay về trong ký ức.',
    tags: ['#Autumn', '#Longing', '#Memory'],
    icon: Wind,
    gradient: 'from-orange-200/22 via-rose-100/14 to-amber-100/10',
    accent: 'rgba(250, 180, 150, 0.55)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 19,
    name: 'Nghiêm Thảo Nguyên',
    meaning: 'Thảo nguyên hoang — khoảng xanh mở đón cả bầu trời.',
    tags: ['#Meadow', '#Open', '#Green'],
    icon: Trees,
    gradient: 'from-green-200/22 via-emerald-100/14 to-lime-100/10',
    accent: 'rgba(165, 235, 170, 0.55)',
    span: 'md:col-span-3 md:row-span-2',
  },
  {
    id: 20,
    name: 'Nghiêm Thảo Chi',
    meaning: 'Một nhánh cỏ — nhỏ bé, riêng biệt, và trọn vẹn là chính mình.',
    tags: ['#Grass', '#Branch', '#Humble'],
    icon: Leaf,
    gradient: 'from-lime-200/20 via-green-100/12 to-white/8',
    accent: 'rgba(180, 235, 160, 0.5)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 21,
    name: 'Nghiêm Mai Thương',
    meaning: 'Tình mai — sự dịu dàng dành cho bông hoa đầu tiên của năm.',
    tags: ['#Plum', '#Love', '#Tender'],
    icon: Heart,
    gradient: 'from-pink-200/24 via-rose-100/14 to-white/8',
    accent: 'rgba(255, 170, 200, 0.6)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 22,
    name: 'Nghiêm Nhật Linh',
    meaning: 'Linh hồn mặt trời — một tâm hồn nhỏ sáng mà ban ngày theo sau.',
    tags: ['#Sun', '#Spirit', '#Bright'],
    icon: Sun,
    gradient: 'from-amber-200/24 via-orange-100/14 to-rose-100/10',
    accent: 'rgba(255, 200, 140, 0.6)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 23,
    name: 'Nghiêm Bích Ngọc',
    meaning: 'Ngọc bích — sắc xanh sâu mát của điều vốn dĩ luôn quý giá.',
    tags: ['#Jade', '#Green', '#Precious'],
    icon: Gem,
    gradient: 'from-emerald-200/24 via-teal-100/14 to-white/10',
    accent: 'rgba(150, 235, 200, 0.6)',
    span: 'md:col-span-3 md:row-span-1',
  },
  {
    id: 24,
    name: 'Nghiêm Thu Uyên',
    meaning: 'Thu uyên — mùa hiểu thấu chính mình một cách trọn vẹn.',
    tags: ['#Autumn', '#Deep', '#Knowing'],
    icon: GraduationCap,
    gradient: 'from-orange-200/22 via-rose-100/14 to-amber-100/10',
    accent: 'rgba(250, 175, 145, 0.55)',
    span: 'md:col-span-3 md:row-span-1',
  },
];
